<?php

namespace HasanHawary\DynamicCli\Support\Generators;

use Illuminate\Support\Str;

class RouteRegistrar extends AbstractStubGenerator
{
    /**
     * @param array{line:callable, info:callable, warn:callable} $callbacks
     */
    public function register(string $studly, string $routeTarget, array &$created, array $callbacks): void
    {
        $line = $callbacks['line'];
        $info = $callbacks['info'];
        $warn = $callbacks['warn'];

        $routeFile = base_path('routes/' . $routeTarget . '.php');
        $uri = Str::kebab(Str::pluralStudly($studly));
        $controllerFqn = 'App\\Http\\Controllers\\' . $studly . 'Controller';
        $routeLine = $routeTarget === 'api'
            ? "Route::apiResource('$uri', \\" . $controllerFqn . '::class);'
            : "Route::resource('$uri', \\" . $controllerFqn . '::class);';

        if (file_exists($routeFile)) {
            $content = file_get_contents($routeFile);
            if (!str_contains($content, $controllerFqn)) {
                $append = "\n// Generated by dynamic-cli on " . date('Y-m-d H:i:s') . "\n" . $routeLine . "\n";
                file_put_contents($routeFile, $content . $append);
                $created[] = 'Route: ' . $routeTarget;
                $info("Appended route to routes/$routeTarget.php -> $uri");
            } else {
                $line("- Skipped route (already contains $controllerFqn)");
            }
        } else {
            $warn("routes/$routeTarget.php not found. Skipped route registration.");
        }
    }
}
