<?php

namespace HasanHawary\DynamicCli\Support\Generators;

use Illuminate\Support\Str;

class RouteRegistrar extends AbstractStubGenerator
{
    /**
     * @param array{line:callable, info:callable, warn:callable} $callbacks
     */
    public function generate(array $params, bool $force, array &$created, array $callbacks): void
    {
        $routeTarget = $params['route'];
        $routeFile = base_path('routes/' . $routeTarget . '.php');
        $uri = Str::kebab(Str::pluralStudly($params['studly']));

        $namespace = config('dynamic-cli-dynamic-cli.namespaces.controller') . "\\{$params['group']}";
        $controllerFqn = "$namespace\\{$params['studly']}Controller";

        $routeLine = "";
        $routeLine .="\n";
        $routeLine .="\n";
        $routeLine .="\n";
        $routeLine = $routeTarget === 'api'
            ? "Route::apiResource('$uri', \\" . $controllerFqn . '::class);'
            : "Route::resource('$uri', \\" . $controllerFqn . '::class);';

        if (file_exists($routeFile)) {
            $content = file_get_contents($routeFile);
            if (!str_contains($content, $controllerFqn)) {
                $append = "\n// Generated by dynamic-cli-dynamic-cli on " . date('Y-m-d H:i:s') . "\n" . $routeLine . "\n";
                file_put_contents($routeFile, $content . $append);
                $created[] = 'Route: ' . $routeTarget;
            }
        }
    }

}
